### ISSUE TITLE
Question about model size constraint

### ISSUE THREAD

**Issue by skeletondyh** [mit-han-lab/haq#12]
Dear authors,

I notice in the first two lines of Table 6 that your searched model has a model size even smaller than 2-bits quantization but a much higher accuracy. Can you illustrate your quantization policy under this constraint? It's a little strange to me because it seems your minimum bitwidth choice is 2 in the paper.

Thank you

**Comment by kuan-wang** [comment]
Hi, we already illustrate this policy in Figure-5 in our paper, where you can the last layer is quantized to 1-bit. And the last layer of MB-V2 has nearly 1/3 parameters of the model, so 1-bit quantizaiton will allocate more space for other layers. By the way, we set the bitwidth choices to 1~6 for resnet50 because the model is large enough for 1-bit quantization and 6-bit is absolutely no loss of accuracy.
